const productos = [
    {
        id: 1,
        productName: "Auriculares",
        price: 5800,
        quanty: 1,
        img: "../E-commerce-Perricentro/html/img/artculoscosmticosecommerceperricentro/Hair_care_1.PNG",
    },
    {
        id: 2,
        productName: "CPU",
        price: 450000,
        quanty: 1,
        img: "../E-commerce-Perricentro/html/img/artculoscosmticosecommerceperricentro/Hair_care_2.PNG",
    },
    {
        id: 3,
        productName: "Microfono Parlante",
        price: 25000,
        quanty: 1,
        img: "../E-commerce-Perricentro/html/img/artculoscosmticosecommerceperricentro/Hair_care_3.PNG",
    },
    // {
    //     id: 4,
    //     productName: "Mouse",
    //     price: 3000,
    //     quanty: 10,
    //     img: "../client/media/mous.webp",
    // },
    {
        id: 5,
        productName: "Mouse Color",
        price: 4500,
        quanty: 1,
        img: "../E-commerce-Perricentro/html/img/artculoscosmticosecommerceperricentro/Lips_care_1.PNG",
    },
    // {
    //     id: 6,
    //     productName: "Mouse Negro",
    //     price: 4000,
    //     quanty: 10,
    //     img: "../client/media/mouse-negro.jpg",
    // },
    {
        id: 7,
        productName: "Parlante JBL",
        price: 36000,
        quanty: 1,
        img: "../E-commerce-Perricentro/html/img/artculoscosmticosecommerceperricentro/Lips_care_2.PNG",
    },
    {
        id: 8,
        productName: "Pc Gamer",
        price: 800000,
        quanty: 1,
        img: "../E-commerce-Perricentro/html/img/artculoscosmticosecommerceperricentro/Nails_care_1.PNG",
    },
    {
        id: 9,
        productName: "Silla Gamer",
        price: 68000,
        quanty: 1,
        img: "../E-commerce-Perricentro/html/img/artculoscosmticosecommerceperricentro/Nails_care_2.PNG",
    },
    {
        id: 10,
        productName: "Teclado",
        price: 4200,
        quanty: 1,
        img: "../E-commerce-Perricentro/html/img/artculoscosmticosecommerceperricentro/Nails_care_3.PNG",
    },
];